services:
  api:
    image: oven/bun
    ports:
      - 8081:80
    volumes:
      - ./src:/app/src
    command: bun --watch /app/src/index.ts

  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restpastrop
      - POSTGRES_USER=restpastrop

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin:rw
    environment:
      - POSTGRES_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=admin@mail.me
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  pgadmin-data:
  db-data:
